# Generated by Django 4.1.1 on 2023-02-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_category', models.CharField(max_length=50)),
                ('task_label', models.CharField(max_length=50)),
                ('task_name', models.CharField(max_length=150)),
                ('task_status', models.CharField(choices=[('I', 'Inprocces'), ('F', 'Finished'), ('C', 'Canceled')], max_length=1)),
                ('task_description', models.CharField(help_text='Ensure you provide some description of the ingredients', max_length=500)),
                ('task_duration', models.DurationField()),
                ('task_repeatation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_key', models.SmallIntegerField(default=10)),
            ],
        ),
    ]
